### ISSUE TITLE
Bug in all_descendant()

### ISSUE THREAD

**Issue by maxime-baclac** [carj/pyPreservica#19]
Hello!

the parent_ref value is a string for the first 100 iterations when iterating through entity.all_descendants(folder)
The value becomes an object starting at iteration 101... seems like something is going on with the generator function subsequent calls....

see attached image
![image](https://github.com/carj/pyPreservica/assets/168654656/8a70f42e-d9f9-4101-9978-b7d36e5da1dc)

debugger
![image](https://github.com/carj/pyPreservica/assets/168654656/4e104cee-d41e-4503-bd19-e216c868cbff)

code (which is close to the online example)
![image](https://github.com/carj/pyPreservica/assets/168654656/49ea3f17-837c-41b3-83a1-cceb9a6842a5)

**Comment by carj** [comment]
Hi

I managed to reproduce the issue.

I have published a new version of pyPreservica 

https://pypi.org/project/pyPreservica/2.7.0/

Could you update your version to 2.7.0 and try again.

pip install --upgrade pyPreservica

**Comment by carj** [comment]
I used the following to test the fix.

```
from pyPreservica import *

client = EntityAPI()

i : int = 0
for e in filter(only_assets, client.all_descendants(None)):
    i = i + 1
    print(i, e.parent)
```

**Comment by maxime-baclac** [comment]
I padded the error, but your timely update is much appreciated.

**Comment by carj** [comment]
closed.
