### ISSUE TITLE
delete_asset(), validation workflow, mail

### ISSUE THREAD

**Issue by joelthill** [carj/pyPreservica#6]
Hi James,

I was using delete_asset() with both an operator and a manager's password configured in credentials.properties.
Even though the call resulted ultimately in the expected deletion, there were still mails sent to the manager asking him to validate manually. In most cases, these wokflows have already been processed by the time she activates the validation link.

Is this a feature or a bug?

(in the meantime, I just emptied the deletion workflow instance's "Confirmation Email Address" field.)

cheers
Joel

**Comment by carj** [comment]
I don't think there is anything that pyPreservica can do in this case. The workflow on Preservica has been setup to send an email and the API call just starts the delete workflow. I think removing the email address as you have done is the only option.

**Comment by joelthill** [comment]
ok. makes sense for me.
j.
