### ISSUE TITLE
EntityAPI : 'str' has no attribute 'trim'

### ISSUE THREAD

**Issue by redbeks** [carj/pyPreservica#7]
Hi James,

Thank you for your work.
It seems there is the use of the trim() function, not available in Python language in the source code, instead of the strip() function.
e.g. in the EntityAPI in the __export_opex_start__() function, which the execution is giving the following error: 

File "venv\lib\site-packages\pyPreservica\entityAPI.py", line 150, in __export_opex_start__
    value = kwargs.get("IncludeContent").trim()
AttributeError: 'str' object has no attribute 'trim'. Did you mean: 'strip'?

thanks,
R.

**Comment by carj** [comment]
Hi
Thanks for the bug report, i have fixed the problem and uploaded a new version 1.2.3

Java code crept in somehow.
